coordinator=false
http-server.http.port=8080

# Container limit = 1g → heap 768M → max 500MB per query per node
query.max-memory-per-node=500MB
query.max-total-memory-per-node=700MB

task.concurrency=4
task.max-worker-threads=6
exchange.compression-codec=LZ4

spill-enabled=true
spiller-spill-path=/tmp/trino-spill
max-spill-per-node=2GB

discovery.uri=http://trino-coordinator:8080